#!/usr/bin/env python
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
regex = '(?:(?P<prefix>feature|hotfix)\/)?(?P<issue>(?:[A-Z]+|wrike)-\d+)'
if re.match(regex, branch):
    issue = re.match(regex, branch).group('issue')
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        if not commit_msg.startswith(issue):
            fh.seek(0, 0)
            fh.write('%s: %s' % (issue, commit_msg))
elif branch != 'master' and branch != 'dev' and branch != 'tmp':
    print 'Incorrect branch name'
    sys.exit(1)